version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::325013156662:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-1UCCQ1VILZFKW"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::684521831782:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-T754IYCEV6GC"
cloudformation_execution_role = "arn:aws:iam::684521831782:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-ICN0UGBES43K"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-lrl2yj2eoaww"
image_repository = ""
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::315295172276:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-RL9EL9KIALG1"
cloudformation_execution_role = "arn:aws:iam::315295172276:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-J7P1MK82035K"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-lqmybsanfuta"
image_repository = ""
region = "us-east-1"
